# Generated by Django 3.1.2 on 2020-10-09 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquirer',
            fields=[
                ('full_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=2)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_amortization', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_term', models.IntegerField()),
                ('sum_payments', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_start_date', models.DateField(default=datetime.date(2020, 10, 9))),
                ('first_payment_date', models.DateField()),
                ('loan_maturity_date', models.DateField()),
                ('inquirer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.inquirer')),
            ],
        ),
    ]
